# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [];
  boot.loader.timeout = 3;

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/64765921-abaf-4401-be91-6b9db3a2217c";
      fsType = "btrfs";
      options = [ "subvol=root" "compress-force=zstd" "noatime" "discard=async"  ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/64765921-abaf-4401-be91-6b9db3a2217c";
      fsType = "btrfs";
      options = [ "subvol=nix" "compress-force=zstd" "noatime" "discard=async"];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/64765921-abaf-4401-be91-6b9db3a2217c";
      fsType = "btrfs";
      options = [ "subvol=home" "compress-force=zstd" "noatime" "discard=async" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3012-5FA2";
      fsType = "vfat";
    };
  
  # fileSystems."/swap".options = [ "noatime" ];

  swapDevices = [ { device = "/swap/swapfile"; } ];

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.firmware = [ pkgs.rtw89-firmware ];
  hardware.openrazer.enable = true;
  
  
  hardware.bluetooth.enable = true;
  hardware.bluetooth.hsphfpd.enable = true;
  # Pipewire config
  hardware.pulseaudio.enable = false;
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    # No idea if I need this
    alsa.support32Bit = true;
    pulse.enable = true;

    # High quality BT calls
    media-session.config.bluez-monitor.rules = [
      {
        # Matches all cards
        matches = [{ "device.name" = "~bluez_card.*"; }];
        actions = {
          "update-props" = {
            "bluez5.auto-connect" = [ "a2dp_sink" ];
          };
        };
      }
      {
        matches = [
          # Matches all sources
          { "node.name" = "~bluez_input.*"; }
          # Matches all outputs
          { "node.name" = "~bluez_output.*"; }
        ];
        actions = {
          "node.pause-on-idle" = false;
        };
      }
    ];
  };
  # users.users.frnks.extraGroups = [ "plugdev" ];
  # hardware.pulseaudio.enable = false;
}
